include:
  - package:flutter_lints/flutter.yaml
  - package:bloc_lint/recommended.yaml

bloc:
  rules:
    - avoid_flutter_imports
    - avoid_public_bloc_methods
    - avoid_public_fields
    - prefer_bloc
    - prefer_void_public_cubit_methods

linter:

  rules:
    - prefer_single_quotes
    - always_use_package_imports
analyzer:
  errors:
    strict_top_level_inference: ignore
