include:
  - package:flutter_lints/flutter.yaml
  - package:bloc_lint/recommended.yaml

bloc:
  rules:
    - avoid_flutter_imports
    - avoid_public_bloc_methods
    - avoid_public_fields
    - prefer_bloc
    - prefer_void_public_cubit_methods

linter:

  rules:
    #    - sort_constructors_first
    #    - sort_unnamed_constructors_first
    #    - sort_pub_dependencies
    #    - sort_child_properties_last
    - prefer_single_quotes
    - always_use_package_imports
    - always_declare_return_types

analyzer:





