// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: String.fromEnvironment("FIREBASE_API_KEY_WEB"),
    appId: String.fromEnvironment("FIREBASE_APP_ID_WEB"),
    messagingSenderId: '1073563434029',
    projectId: 'cafe-pra-ja',
    authDomain: 'cafe-pra-ja.firebaseapp.com',
    storageBucket: 'cafe-pra-ja.firebasestorage.app',
    measurementId: 'G-47PMSCH1F8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: String.fromEnvironment("FIREBASE_API_KEY_ANDROID"),
    appId: String.fromEnvironment("FIREBASE_APP_ID_ANDROID"),
    messagingSenderId: String.fromEnvironment("FIREBASE_MESSAGING_SENDER_ID"),
    projectId: String.fromEnvironment("FIREBASE_PROJECT_ID"),
    storageBucket: String.fromEnvironment("STORAGE_BUCKET"),
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: String.fromEnvironment("FIREBASE_API_KEY_IOS"),
    appId: String.fromEnvironment("FIREBASE_APP_ID_IOS"),
    messagingSenderId: String.fromEnvironment("FIREBASE_MESSAGING_SENDER_ID"),
    projectId: String.fromEnvironment("FIREBASE_PROJECT_ID"),
    storageBucket: String.fromEnvironment("STORAGE_BUCKET"),
    iosBundleId: 'com.example.cafePraJa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: String.fromEnvironment("FIREBASE_API_KEY_MACOS"),
    appId: String.fromEnvironment("FIREBASE_APP_ID_MACOS"),
    messagingSenderId: String.fromEnvironment("FIREBASE_MESSAGING_SENDER_ID"),
    projectId: String.fromEnvironment("FIREBASE_PROJECT_ID"),
    storageBucket: String.fromEnvironment("STORAGE_BUCKET"),
    iosBundleId: 'com.example.cafePraJa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: String.fromEnvironment("FIREBASE_API_KEY_WINDOWS"),
    appId: String.fromEnvironment("FIREBASE_APP_ID_WINDOWS"),
    messagingSenderId: String.fromEnvironment("FIREBASE_MESSAGING_SENDER_ID"),
    projectId: String.fromEnvironment("FIREBASE_PROJECT_ID"),
    authDomain: 'cafe-pra-ja.firebaseapp.com',
    storageBucket: String.fromEnvironment("STORAGE_BUCKET"),
    measurementId: 'G-BKLE6EGH3F',
  );
}
